name: flutter_google_maps_clusters
description: An example showing how to cluster markers on Google Maps.

version: 2.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Google maps
  google_maps_flutter: ^2.0.5

  # Map markers clustering
  fluster: ^1.2.0

  # Cache manager
  flutter_cache_manager: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
